# Generated by Django 5.0.1 on 2024-05-28 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, null=True)),
                ('brand_name', models.CharField(max_length=200, null=True)),
                ('soh', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Item Name',
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('remarks', models.CharField(max_length=50, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemdetails')),
            ],
            options={
                'verbose_name_plural': 'Item',
            },
        ),
    ]
