# Generated by Django 5.0.1 on 2024-06-16 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='itemBase_code',
        ),
    ]
