# Generated by Django 5.0.1 on 2024-05-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_item_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemname',
            name='brand_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='itemname',
            name='item_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='itemname',
            name='uom',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
