# Generated by Django 5.0.1 on 2024-06-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_item_itembase_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='uom',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itembase',
            name='uom',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
