# Generated by Django 5.0.1 on 2024-05-29 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_item_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-date_added'], 'verbose_name_plural': 'Item'},
        ),
    ]
