# Generated by Django 5.0.1 on 2024-05-22 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_itemname_brand_name_alter_itemname_item_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Item'},
        ),
        migrations.AlterModelOptions(
            name='itemname',
            options={'verbose_name_plural': 'Item Name'},
        ),
    ]
