# Generated by Django 5.0.1 on 2024-06-24 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_client_department_item_staff_name_item_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembase',
            name='total_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='client_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.client'),
        ),
        migrations.AlterField(
            model_name='item',
            name='department_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.department'),
        ),
        migrations.AlterField(
            model_name='item',
            name='staff_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
