# Generated by Django 5.0.1 on 2024-06-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_itembase_total_value_alter_item_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembase',
            name='brand_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
