# Generated by Django 5.0.1 on 2024-06-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemdetails',
            table='item',
        ),
    ]
