# Generated by Django 5.0.1 on 2024-05-25 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_itemname_uom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemname',
            options={'ordering': ['item_name'], 'verbose_name_plural': 'Item Name'},
        ),
        migrations.CreateModel(
            name='Item_SOH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soh', models.IntegerField()),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemname')),
            ],
        ),
    ]
