# Generated by Django 5.0.1 on 2024-06-28 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_itembase_brand_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcode',
            options={'ordering': ['-code']},
        ),
    ]
