# Generated by Django 5.0.1 on 2024-05-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_itemname_options_item_soh'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item_soh',
            options={'verbose_name_plural': 'Item SOH'},
        ),
        migrations.AddField(
            model_name='item',
            name='remarks',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
