# Generated by Django 5.0.1 on 2024-06-28 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_itemcode_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcode',
            options={'ordering': ['code']},
        ),
    ]
