# Generated by Django 5.0.1 on 2024-05-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_item_soh_options_item_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='remarks',
            field=models.CharField(default='DEDUCTED', max_length=50, null=True),
        ),
    ]
