# Generated by Django 5.0.1 on 2024-05-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_item_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemname',
            name='item_code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
